# To build:
# docker build -t database:v1 -f docker/Dockerfile.db .
#
# To run:
# docker run -p 3306:3306 --env MYSQL_ROOT_PASSWORD=Welcome1 -it database:v1
FROM mysql:5.7
ADD ./setup.sql /docker-entrypoint-initdb.d/setup.sql
