# NOT WORKING!!!!
# To build:
# docker build -t sod-service -f docker/Dockerfile.dev .
#
# To run:
# docker run -p 8080:8080 -it sod-service
FROM centos:6
MAINTAINER cesareg.borjon@gmail.com

ENV JAVA_VERSION 8u31
ENV BUILD_VERSION b13

# Upgrading system
RUN yum -y upgrade
RUN yum -y install wget

# Downloading Java
RUN wget --no-cookies --no-check-certificate --header "Cookie: oraclelicense=accept-securebackup-cookie" "http://download.oracle.com/otn-pub/java/jdk/$JAVA_VERSION-$BUILD_VERSION/jdk-$JAVA_VERSION-linux-x64.rpm" -O /tmp/jdk-8-linux-x64.rpm

RUN yum -y install /tmp/jdk-8-linux-x64.rpm

RUN alternatives --install /usr/bin/java jar /usr/java/latest/bin/java 200000
RUN alternatives --install /usr/bin/javaws javaws /usr/java/latest/bin/javaws 200000
RUN alternatives --install /usr/bin/javac javac /usr/java/latest/bin/javac 200000

ENV JAVA_HOME /usr/java/latest


#User IL = Interactive labs
ENV BASE_USER il
ENV USER_HOME /home/$BASE_USER
#Default to dev if DOCENG_ENV is not passed in at runtime

# Install dependencies
RUN yum install -y git python-2.7.5 curl wget tar unzip

# Install
RUN cd /tmp && wget http://nodejs.org/dist/v0.12.3/node-v0.12.3-linux-x64.tar.gz
RUN cd /usr && tar --strip-components 1 -xzf /tmp/node-v0.12.3-linux-x64.tar.gz

# Create our doceng user
RUN useradd $BASE_USER

#make the base_user the owner of all its HOME files, including the .ssh and DOCENG_BASE_SRC dirs
RUN chown -R $BASE_USER:$BASE_USER $USER_HOME

#app specific information.
#this will be the name of the micro-service
ENV MODULE service
ENV JAR_NAME sod_project.jar
ENV MODULE_SOURCE ${USER_HOME}/${MODULE}

# 8080 is the port the jetty server is currently set to listen
ENV REGISTRATION_API_PORT 8080

# use -P/-p at run time to expose this port from the Docker host
EXPOSE $REGISTRATION_API_PORT

# add in the source files
RUN echo 'Creating folder '
RUN mkdir -p ${MODULE_SOURCE}
RUN echo 'Copying files'
COPY ./project/target/${JAR_NAME} ${MODULE_SOURCE}
RUN chmod 755 ${MODULE_SOURCE}/${JAR_NAME}


WORKDIR ${MODULE_SOURCE}

# make doceng the owner of all the source files, so when mvn clean install package runs it can create the target/classes dir
RUN chown -R ${BASE_USER}:${BASE_USER} ${MODULE_SOURCE}

USER $BASE_USER

#ENTRYPOINT ["java", "-jar", "sod_project.jar"]
